### ISSUE TITLE
Linguagem utilizada

### ISSUE THREAD

**Issue by ForceTower** [lublot/Paciencia#1]
Este projeto usa Java.

Estou ofendido pela escolha da linguagem.

Kotlin >>>>>>>> Abismos >>>>>>>> Java

**Comment by lublot** [comment]
@ForceTower Precisamos falar sobre a doutrinação Javista nas universidades!! #JavaNão!

Lamento o inconveniente, mas fui obrigado e preciso me formar.

**Comment by ForceTower** [comment]
É verdade, sinto muito pela sua dor.

@ProfessorPadroesProjetos, creio que os alunos deveriam poder escolher uma linguagem estaticamente tipada.
Ou, no mínimo, deixar o pessoal usar kotlin que é compatível com a JVM e tem menos burocracias para um print.

Fora à doutrinação Javista!
